### ISSUE TITLE
Crash with bcl2fastq.additionnal.arguments enabled (v2.3)

### ISSUE THREAD

**Issue by ajeffs** [GenomiqueENS/aozan#15]
Setting bcl2fastq.additionnal.arguments [sic] in aozan.conf results in the following error (v2.3-SNAPSHOT revision heads/master-0-g120640f):

"[Aozan] demultiplexer: Failed demultiplexing for run 231006_M01795_1127_000000000-LB895, catch exception <type 'exceptions.AttributeError'> ('list' object has no attribute 'extends') Failed demultiplexing for run 231006_M01795_1127_000000000-LB895, catch exception <type 'exceptions.AttributeError'> ('list' object has no attribute 'extends')
 Stacktrace: 
Traceback (most recent call last):
  File "/home/aozan/aozan_progs/lib/jython-standalone-2.7.0.jar/aozan.py", line 428, in launch_steps
    if demux_run.demux(run_id, conf):
  File "/home/aozan/aozan_progs/lib/jython-standalone-2.7.0.jar/demux_run.py", line 860, in demux
    if not demux_run_standalone(run_id, input_run_data_path, fastq_output_dir, bcl2fastq_samplesheet_path,
  File "/home/aozan/aozan_progs/lib/jython-standalone-2.7.0.jar/demux_run.py", line 535, in demux_run_standalone
    cmd = create_bcl2fastq_command_line(run_id, bcl2fastq_executable_path, input_run_data_path, fastq_output_dir,
  File "/home/aozan/aozan_progs/lib/jython-standalone-2.7.0.jar/demux_run.py", line 493, in create_bcl2fastq_command_line
    args.extends(additional_args.split(' '))
AttributeError: 'list' object has no attribute 'extends'"

I'm guessing the misspelling of "additional" should be kept as-is.

I'm also guessing the syntax of the property is the bcl2fastq option without the leading "--" (it crashes with or without a leading "--"), e.g:
bcl2fastq.additionnal.arguments=auto-set-to-zero-barcode-mismatches

The  bcl2fastq option above is not documented, but works fine when bcl2fastq is launched manually (it automatically sets the barcode mismatch to 0 if a collision is detected, which allows bcl2fastq, and therefore Aozan, to continue demuxing).

Any advice on how we can get the bcl2fastq.additionnal.arguments property working would be very much appreciated!

Regards,
Aaron.

**Comment by jourdren** [comment]
Hi @ajeffs,

The issue came from a typo in `demux_run.py`. It was fixed by b0fe8 commit.

We do not anymore publish binaries for Aozan 2. However I can provide it to you If you if you ask me.

Best regards,

Laurent.

**Comment by ajeffs** [comment]
Hi @jourdren , cheers for fixing this, much appreciated!

We prefer to still use v2 for our MiSeq runs, so if I may please request a v2 binary with the fix then that would be awesome.

All the best,

Aaron.

**Comment by jourdren** [comment]
Hi @ajeffs,

Aozan 2.2.2 that patch your issue is available for download at the following location :
https://github.com/GenomiqueENS/aozan/releases/tag/v3.0.1

Best regards,

Laurent.

**Comment by ajeffs** [comment]
Fantastic, thanks @jourdren !
