### ISSUE TITLE
Minor: customized setting mail.footer not taken into account

### ISSUE THREAD

**Issue by loraine-gueguen** [GenomiqueENS/aozan#23]
The customized setting `mail.footer` in `aozan.conf` is not taken into account. The emails sent have the default footer, not the one defined in `aozan.conf`.

`mail.footer=\n\nAozan on ABiMS.\n`

This setting worked fine with aozan-2.3-SNAPSHOT. This does not work anymore with aozan-3.1-SNAPSHOT, with legacy aozan2 configuration

**Comment by jourdren** [comment]
Fixed with cdea3bb commit.
