### ISSUE TITLE
Minor: Generate a line in the logs each time aozan is launched

### ISSUE THREAD

**Issue by loraine-gueguen** [GenomiqueENS/aozan#26]
it might be interesting to generate a line in the logs each time aozan is launched, even if no new run is detected, to make sure that aozan has run properly. This doesn't seem to be the case at present, unless the logs are playing tricks on me again? (see https://github.com/GenomiqueENS/aozan/issues/16)

**Comment by jourdren** [comment]
Fixed with the 3d49b10 commit.
